services:
  user_service_db:
    image: postgres:latest
    networks:
      - local-net
    container_name: user_service_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

  user_service:
    build: .
    networks:
      - kafka-net
      - local-net
    container_name: user_service
    restart: always
    depends_on:
      user_service_db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8001:8001"

volumes:
  pgdata:

networks:
  kafka-net:
    name: kafka-net
    driver: bridge
    external: true
  local-net:
    driver: bridge
